name: cleantemplate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #utils
  device_preview: ^1.1.0
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  get: ^4.6.5
  get_it: ^7.6.0
  google_fonts: ^4.0.3
  url_launcher: ^6.1.12
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  logger: ^1.4.0
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5

  #image
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

  #ui
  figma_squircle: ^0.5.3
  flutter_animate: ^4.2.0+1
  animations: ^2.0.7
  liquid_swipe: ^3.1.0
  coupon_uikit: ^0.2.0
  flutter_rating_bar: ^4.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_runner: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    # - assets/icons/
    - assets/gifs/
